title: Adeel Sheikh # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Game development enthusiast having a diversified experience in leading, conceptualizing and publishing games. Having more than 4 years of experience in the industry. Have worked on technologies like Unity3D and Cocos2D. A very quick learner and a great team player. 
  <br><br>
  <a href="https://www.linkedin.com/in/mohammed-adeel-sheikh-54533355/">View My LinkedIn Profile</a> 
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
